// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";

export const Engine = new SyncConcept();

import { getDb } from "@utils/database.ts";

import CollaboratorsConcept from "./Collaborators/CollaboratorsConcept.ts";
import LikertSurveyConcept from "./LikertSurvey/LikertSurveyConcept.ts";
import UserAuthConcept from "./UserAuth/UserAuthConcept.ts";
import RelationshipConcept from "./Relationship/RelationshipConcept.ts";
import NotesConcept from "./Notes/NotesConcept.ts";
import OccasionNotesConcept from "./OccasionNotes/OccasionNotesConcept.ts";
import ProfileConcept from "./Profile/ProfileConcept.ts";
import RequestingConcept from "./Requesting/RequestingConcept.ts";
import SessioningConcept from "./Sessioning/SessioningConcept.ts";
import MemoryGalleryConcept from "./MemoryGallery/MemoryGalleryConcept.ts";
import TaskConcept from "./Task/TaskConcept.ts";
import TaskChecklistConcept from "./TaskChecklist/TaskChecklistConcept.ts";
import SuggestionEngineConcept from "./SuggestionEngine/SuggestionEngineConcept.ts";
import OccasionConcept from "./Occasion/OccasionConcept.ts";

export type { default as CollaboratorsConcept } from "./Collaborators/CollaboratorsConcept.ts";
export type { default as LikertSurveyConcept } from "./LikertSurvey/LikertSurveyConcept.ts";
export type { default as UserAuthConcept } from "./UserAuth/UserAuthConcept.ts";
export type { default as RelationshipConcept } from "./Relationship/RelationshipConcept.ts";
export type { default as NotesConcept } from "./Notes/NotesConcept.ts";
export type { default as OccasionNotesConcept } from "./OccasionNotes/OccasionNotesConcept.ts";
export type { default as ProfileConcept } from "./Profile/ProfileConcept.ts";
export type { default as RequestingConcept } from "./Requesting/RequestingConcept.ts";
export type { default as SessioningConcept } from "./Sessioning/SessioningConcept.ts";
export type { default as MemoryGalleryConcept } from "./MemoryGallery/MemoryGalleryConcept.ts";
export type { default as TaskConcept } from "./Task/TaskConcept.ts";
export type { default as TaskChecklistConcept } from "./TaskChecklist/TaskChecklistConcept.ts";
export type { default as SuggestionEngineConcept } from "./SuggestionEngine/SuggestionEngineConcept.ts";
export type { default as OccasionConcept } from "./Occasion/OccasionConcept.ts";

// Initialize the database connection
export const [db, client] = await getDb();

export const Collaborators = Engine.instrumentConcept(
  new CollaboratorsConcept(db)
);
export const LikertSurvey = Engine.instrumentConcept(
  new LikertSurveyConcept(db)
);
export const UserAuth = Engine.instrumentConcept(new UserAuthConcept(db));
export const Relationship = Engine.instrumentConcept(
  new RelationshipConcept(db)
);
export const Notes = Engine.instrumentConcept(new NotesConcept(db));
export const OccasionNotes = Engine.instrumentConcept(
  new OccasionNotesConcept(db)
);
export const Profile = Engine.instrumentConcept(new ProfileConcept(db));
export const Requesting = Engine.instrumentConcept(new RequestingConcept(db));
export const Sessioning = Engine.instrumentConcept(new SessioningConcept(db));
export const MemoryGallery = Engine.instrumentConcept(
  new MemoryGalleryConcept(db)
);
export const Task = Engine.instrumentConcept(new TaskConcept(db));
export const TaskChecklist = Engine.instrumentConcept(
  new TaskChecklistConcept(db)
);
export const SuggestionEngine = Engine.instrumentConcept(
  new SuggestionEngineConcept(db)
);
export const Occasion = Engine.instrumentConcept(new OccasionConcept(db));
